--WAQTD employees whose hiredate is after SCOTT but before FORD
 SELECT *
 FROM EMP
 WHERE HIREDATE > (
 SELECT HIREDATE
 FROM EMP 
 WHERE ENAME = 'SCOTT') AND HIREDATE < 
 (SELECT HIREDATE 
 FROM EMP
 WHERE ENAME = 'FORD'); 